
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'inv_log'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'inv_log'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  #- "dbt_packages"

models:
  inv_log:
    #+ config:
    #  + exclude_views: ['stg_sub_info','stg_shipping_cost','stg_order_invoice','stg_inventory','stg_customers']
    customer:
      +materialized: view
    product:
      +materialized: view
    #triggers:
      
    #  update_final_invoice:
    #    sql: update_final_invoice.sql
    #  +post-hook: {{ post_hooks.update_final_invoice }}
      
    #  update_final_invoice:
    #    materialized: view
    #    +post-hook:
    #      - "{% if target.name == 'postgres' %}select update_final_invoice() {% endif %}"